# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
    builder: html
    configuration: docs/source/conf.py
    fail_on_warning: false

build:
  os: ubuntu-20.04
  tools:
    python: '3.9'
  apt_packages:
    - python3-gst-1.0
    - python3-numpy
    - gstreamer1.0-plugins-good
    - gstreamer1.0-plugins-ugly
    - gstreamer1.0-plugins-bad
    - gstreamer1.0-alsa
    - gstreamer1.0-plugins-base-apps
    - gstreamer1.0-tools
    - glib-networking
    - gobject-introspection
    - ffmpeg
    - libges-1.0-0
    - libofa0
    - libgirepository1.0-dev
    - libsndfile1-dev
    - libavcodec-dev
    - libavformat-dev
    - libavutil-dev
    - libavresample-dev
    - libcairo2-dev
    - libyaml-dev
    - vamp-examples
    - vamp-plugin-sdk


# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .