apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
      - args:
        - /bin/bash
        - /srv/app/bin/app.sh
        env:
        - name: CELERY_BROKER_URL
          value: redis://broker:6379/0
        - name: CELERY_TASK_ALWAYS_EAGER
          value: "False"
        - name: DEBUG
          value: "False"
        - name: PIP_DOWNLOAD_CACHE
          value: /srv/cache/pip
        - name: POSTGRES_PASSWORD
          value: mysecretpassword
        - name: PYTHONWARNINGS
          value: ignore::DeprecationWarning
        - name: SECRET_KEY
          value: ghv8us2587n97dq&w$c((o5rj_$-9#d-8j#57y_a9og8wux1h7
        - name: bower_storage__packages
          value: /srv/cache/bower
        image: parisson/timeside:latest-dev
        imagePullPolicy: Always
        name: app
        ports:
        - containerPort: 8000
        resources: {}
        volumeMounts:
        #- mountPath: /srv/media
        #  name: app-srv-media
        #  subPath: media
        - mountPath: /srv/static
          name: app-srv-static
          subPath: static
        - mountPath: /var/log/uwsgi
          name: app-log-uwsgi
          subPath: uwsgi
        - mountPath: /var/log/app
          name: app-log-app
          subPath: app
        - mountPath: /srv/cache
          name: app-srv-cache
          subPath: cache
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      #- name: app-srv-media
      #  persistentVolumeClaim:
      #  claimName: app-srv-media
      - name: app-srv-static
        persistentVolumeClaim:
          claimName: app-srv-static
      - name: app-log-uwsgi
        persistentVolumeClaim:
          claimName: app-log-uwsgi
      - name: app-log-app
        persistentVolumeClaim:
          claimName: app-log-app
      - name: app-srv-cache
        persistentVolumeClaim:
          claimName: app-srv-cache
status: {}
