services:

  app:
    image: python:3.7-buster
    volumes:
      - ../requirements-dev.txt:/requirements-dev.txt
    command: bash -c "pip install --upgrade setuptools pip numpy; pip install -r /requirements-dev.txt"
