version: '3'

services:
  websockets:  
    build: ./websockets
    ports:
      - "9031:8000"
    environment:
      - ORIGIN=http://localhost:9080
    command: "yarn run dev"
    volumes:
      - ./websockets:/srv/app/
    user: "root:root"
    env_file:
      - env/debug.env
